/* cambio.c generated by valac 0.34.7, the Vala compiler
 * generated from cambio.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * main.c
 * Copyright (C) 2018 Taylan Branco Meurer <tbmeurer@gmail.com>
 *
 * cambio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * cambio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include "config.h"
#include <stdio.h>
#include <float.h>
#include <math.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define MAIN_TYPE_COLUMN (main_column_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};

struct _MainPrivate {
	gchar** lista_box_presion;
	gint lista_box_presion_length1;
	gint _lista_box_presion_size_;
	gchar** lista_box_volumen;
	gint lista_box_volumen_length1;
	gint _lista_box_volumen_size_;
	gchar** lista_box_masa;
	gint lista_box_masa_length1;
	gint _lista_box_masa_size_;
	gchar** lista_box_fuerza;
	gint lista_box_fuerza_length1;
	gint _lista_box_fuerza_size_;
	gchar** lista_box_tiempo;
	gint lista_box_tiempo_length1;
	gint _lista_box_tiempo_size_;
	gchar** lista_box_velocidad;
	gint lista_box_velocidad_length1;
	gint _lista_box_velocidad_size_;
	gchar** lista_box_longitud;
	gint lista_box_longitud_length1;
	gint _lista_box_longitud_size_;
	gchar** lista_box_densidad;
	gint lista_box_densidad_length1;
	gint _lista_box_densidad_size_;
	gchar** lista_box_area;
	gint lista_box_area_length1;
	gint _lista_box_area_size_;
	GtkEntry* entry_presion_entrada;
	GtkEntry* entry_presion_saida;
	GtkEntry* entry_volumen_entrada;
	GtkEntry* entry_volumen_saida;
	GtkEntry* entry_masa_entrada;
	GtkEntry* entry_masa_saida;
	GtkEntry* entry_fuerza_entrada;
	GtkEntry* entry_fuerza_saida;
	GtkEntry* entry_densidad_entrada;
	GtkEntry* entry_densidad_saida;
	GtkEntry* entry_velocidad_entrada;
	GtkEntry* entry_velocidad_saida;
	GtkEntry* entry_area_entrada;
	GtkEntry* entry_area_saida;
	GtkEntry* entry_longitud_entrada;
	GtkEntry* entry_longitud_saida;
	GtkEntry* entry_tiempo_entrada;
	GtkEntry* entry_tiempo_saida;
	GtkSpinButton* spin_presion;
	GtkSpinButton* spin_masa;
	GtkSpinButton* spin_fuerza;
	GtkSpinButton* spin_volumen;
	GtkSpinButton* spin_densidad;
	GtkSpinButton* spin_area;
	GtkSpinButton* spin_longitud;
	GtkSpinButton* spin_tiempo;
	GtkSpinButton* spin_velocidad;
	GtkComboBox* box_presion_entrada;
	GtkComboBox* box_presion_saida;
	GtkComboBox* box_fuerza_entrada;
	GtkComboBox* box_fuerza_saida;
	GtkComboBox* box_masa_entrada;
	GtkComboBox* box_masa_saida;
	GtkComboBox* box_densidad_entrada;
	GtkComboBox* box_densidad_saida;
	GtkComboBox* box_volumen_entrada;
	GtkComboBox* box_volumen_saida;
	GtkComboBox* box_velocidad_entrada;
	GtkComboBox* box_velocidad_saida;
	GtkComboBox* box_area_entrada;
	GtkComboBox* box_area_saida;
	GtkComboBox* box_longitud_entrada;
	GtkComboBox* box_longitud_saida;
	GtkComboBox* box_tiempo_entrada;
	GtkComboBox* box_tiempo_saida;
	GtkAboutDialog* dialog;
};

typedef enum  {
	MAIN_COLUMN_Presion_enum
} MainColumn;


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY
};
static GType main_column_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define MAIN_UI_FILE PACKAGE_DATA_DIR "/ui/" "cambio.ui"
Main* main_new (void);
Main* main_construct (GType object_type);
static void main_get_variables (Main* self, GtkBuilder* builder);
static void main_criar_liststore_para_combobox (Main* self, GtkComboBox* box, GtkListStore* liststore, gchar** lista, int lista_length1);
void main_on_destroy (GtkWidget* window, Main* self);
void main_on_dialog_close_clicked (GtkWidget* window, Main* self);
void main_on_acerca (GtkWidget* window, Main* self);
static void main_escribir_entrada (Main* self, GtkSpinButton* spin, gchar** lista, int lista_length1, GtkComboBox* box_entrada, GtkEntry* entry_entrada);
static void main_escribir_saida (Main* self, gdouble aux, GtkSpinButton* spin, gchar** lista, int lista_length1, GtkComboBox* box_saida, GtkEntry* entry_saida);
void main_on_but_aplicar_presion_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_fuerza_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_volumen_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_masa_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_densidad_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_velocidad_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_area_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_longitud_clicked (GtkWidget* window, Main* self);
void main_on_but_aplicar_tiempo_clicked (GtkWidget* window, Main* self);
static gint main_main (gchar** args, int args_length1);
static void main_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static GType main_column_get_type (void) {
	static volatile gsize main_column_type_id__volatile = 0;
	if (g_once_init_enter (&main_column_type_id__volatile)) {
		static const GEnumValue values[] = {{MAIN_COLUMN_Presion_enum, "MAIN_COLUMN_Presion_enum", "presion-enum"}, {0, NULL, NULL}};
		GType main_column_type_id;
		main_column_type_id = g_enum_register_static ("MainColumn", values);
		g_once_init_leave (&main_column_type_id__volatile, main_column_type_id);
	}
	return main_column_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	GError * _inner_error_ = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	{
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp0_ = NULL;
		GtkListStore* liststore_presion_e = NULL;
		GtkListStore* _tmp1_ = NULL;
		GtkListStore* liststore_presion_s = NULL;
		GtkListStore* _tmp2_ = NULL;
		GtkListStore* liststore_fuerza_e = NULL;
		GtkListStore* _tmp3_ = NULL;
		GtkListStore* liststore_fuerza_s = NULL;
		GtkListStore* _tmp4_ = NULL;
		GtkListStore* liststore_volumen_e = NULL;
		GtkListStore* _tmp5_ = NULL;
		GtkListStore* liststore_volumen_s = NULL;
		GtkListStore* _tmp6_ = NULL;
		GtkListStore* liststore_masa_e = NULL;
		GtkListStore* _tmp7_ = NULL;
		GtkListStore* liststore_masa_s = NULL;
		GtkListStore* _tmp8_ = NULL;
		GtkListStore* liststore_densidad_e = NULL;
		GtkListStore* _tmp9_ = NULL;
		GtkListStore* liststore_densidad_s = NULL;
		GtkListStore* _tmp10_ = NULL;
		GtkListStore* liststore_velocidad_e = NULL;
		GtkListStore* _tmp11_ = NULL;
		GtkListStore* liststore_velocidad_s = NULL;
		GtkListStore* _tmp12_ = NULL;
		GtkListStore* liststore_area_e = NULL;
		GtkListStore* _tmp13_ = NULL;
		GtkListStore* liststore_area_s = NULL;
		GtkListStore* _tmp14_ = NULL;
		GtkListStore* liststore_longitud_e = NULL;
		GtkListStore* _tmp15_ = NULL;
		GtkListStore* liststore_longitud_s = NULL;
		GtkListStore* _tmp16_ = NULL;
		GtkListStore* liststore_tiempo_e = NULL;
		GtkListStore* _tmp17_ = NULL;
		GtkListStore* liststore_tiempo_s = NULL;
		GtkListStore* _tmp18_ = NULL;
		GtkComboBox* _tmp19_ = NULL;
		GtkListStore* _tmp20_ = NULL;
		gchar** _tmp21_ = NULL;
		gint _tmp21__length1 = 0;
		GtkComboBox* _tmp22_ = NULL;
		GtkListStore* _tmp23_ = NULL;
		gchar** _tmp24_ = NULL;
		gint _tmp24__length1 = 0;
		GtkComboBox* _tmp25_ = NULL;
		GtkListStore* _tmp26_ = NULL;
		gchar** _tmp27_ = NULL;
		gint _tmp27__length1 = 0;
		GtkComboBox* _tmp28_ = NULL;
		GtkListStore* _tmp29_ = NULL;
		gchar** _tmp30_ = NULL;
		gint _tmp30__length1 = 0;
		GtkComboBox* _tmp31_ = NULL;
		GtkListStore* _tmp32_ = NULL;
		gchar** _tmp33_ = NULL;
		gint _tmp33__length1 = 0;
		GtkComboBox* _tmp34_ = NULL;
		GtkListStore* _tmp35_ = NULL;
		gchar** _tmp36_ = NULL;
		gint _tmp36__length1 = 0;
		GtkComboBox* _tmp37_ = NULL;
		GtkListStore* _tmp38_ = NULL;
		gchar** _tmp39_ = NULL;
		gint _tmp39__length1 = 0;
		GtkComboBox* _tmp40_ = NULL;
		GtkListStore* _tmp41_ = NULL;
		gchar** _tmp42_ = NULL;
		gint _tmp42__length1 = 0;
		GtkComboBox* _tmp43_ = NULL;
		GtkListStore* _tmp44_ = NULL;
		gchar** _tmp45_ = NULL;
		gint _tmp45__length1 = 0;
		GtkComboBox* _tmp46_ = NULL;
		GtkListStore* _tmp47_ = NULL;
		gchar** _tmp48_ = NULL;
		gint _tmp48__length1 = 0;
		GtkComboBox* _tmp49_ = NULL;
		GtkListStore* _tmp50_ = NULL;
		gchar** _tmp51_ = NULL;
		gint _tmp51__length1 = 0;
		GtkComboBox* _tmp52_ = NULL;
		GtkListStore* _tmp53_ = NULL;
		gchar** _tmp54_ = NULL;
		gint _tmp54__length1 = 0;
		GtkComboBox* _tmp55_ = NULL;
		GtkListStore* _tmp56_ = NULL;
		gchar** _tmp57_ = NULL;
		gint _tmp57__length1 = 0;
		GtkComboBox* _tmp58_ = NULL;
		GtkListStore* _tmp59_ = NULL;
		gchar** _tmp60_ = NULL;
		gint _tmp60__length1 = 0;
		GtkComboBox* _tmp61_ = NULL;
		GtkListStore* _tmp62_ = NULL;
		gchar** _tmp63_ = NULL;
		gint _tmp63__length1 = 0;
		GtkComboBox* _tmp64_ = NULL;
		GtkListStore* _tmp65_ = NULL;
		gchar** _tmp66_ = NULL;
		gint _tmp66__length1 = 0;
		GtkComboBox* _tmp67_ = NULL;
		GtkListStore* _tmp68_ = NULL;
		gchar** _tmp69_ = NULL;
		gint _tmp69__length1 = 0;
		GtkComboBox* _tmp70_ = NULL;
		GtkListStore* _tmp71_ = NULL;
		gchar** _tmp72_ = NULL;
		gint _tmp72__length1 = 0;
		GtkWindow* window = NULL;
		GObject* _tmp73_ = NULL;
		GtkWindow* _tmp74_ = NULL;
		GObject* _tmp75_ = NULL;
		GtkAboutDialog* _tmp76_ = NULL;
		GtkWindow* _tmp77_ = NULL;
		_tmp0_ = gtk_builder_new ();
		builder = _tmp0_;
		gtk_builder_add_from_file (builder, MAIN_UI_FILE, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (builder);
			goto __catch0_g_error;
		}
		main_get_variables (self, builder);
		gtk_builder_connect_signals (builder, self);
		_tmp1_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_presion_e = _tmp1_;
		_tmp2_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_presion_s = _tmp2_;
		_tmp3_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_fuerza_e = _tmp3_;
		_tmp4_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_fuerza_s = _tmp4_;
		_tmp5_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_volumen_e = _tmp5_;
		_tmp6_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_volumen_s = _tmp6_;
		_tmp7_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_masa_e = _tmp7_;
		_tmp8_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_masa_s = _tmp8_;
		_tmp9_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_densidad_e = _tmp9_;
		_tmp10_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_densidad_s = _tmp10_;
		_tmp11_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_velocidad_e = _tmp11_;
		_tmp12_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_velocidad_s = _tmp12_;
		_tmp13_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_area_e = _tmp13_;
		_tmp14_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_area_s = _tmp14_;
		_tmp15_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_longitud_e = _tmp15_;
		_tmp16_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_longitud_s = _tmp16_;
		_tmp17_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_tiempo_e = _tmp17_;
		_tmp18_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
		liststore_tiempo_s = _tmp18_;
		_tmp19_ = self->priv->box_presion_entrada;
		_tmp20_ = liststore_presion_e;
		_tmp21_ = self->priv->lista_box_presion;
		_tmp21__length1 = self->priv->lista_box_presion_length1;
		main_criar_liststore_para_combobox (self, _tmp19_, _tmp20_, _tmp21_, _tmp21__length1);
		_tmp22_ = self->priv->box_presion_saida;
		_tmp23_ = liststore_presion_s;
		_tmp24_ = self->priv->lista_box_presion;
		_tmp24__length1 = self->priv->lista_box_presion_length1;
		main_criar_liststore_para_combobox (self, _tmp22_, _tmp23_, _tmp24_, _tmp24__length1);
		_tmp25_ = self->priv->box_volumen_entrada;
		_tmp26_ = liststore_volumen_e;
		_tmp27_ = self->priv->lista_box_volumen;
		_tmp27__length1 = self->priv->lista_box_volumen_length1;
		main_criar_liststore_para_combobox (self, _tmp25_, _tmp26_, _tmp27_, _tmp27__length1);
		_tmp28_ = self->priv->box_volumen_saida;
		_tmp29_ = liststore_volumen_s;
		_tmp30_ = self->priv->lista_box_volumen;
		_tmp30__length1 = self->priv->lista_box_volumen_length1;
		main_criar_liststore_para_combobox (self, _tmp28_, _tmp29_, _tmp30_, _tmp30__length1);
		_tmp31_ = self->priv->box_masa_entrada;
		_tmp32_ = liststore_masa_e;
		_tmp33_ = self->priv->lista_box_masa;
		_tmp33__length1 = self->priv->lista_box_masa_length1;
		main_criar_liststore_para_combobox (self, _tmp31_, _tmp32_, _tmp33_, _tmp33__length1);
		_tmp34_ = self->priv->box_masa_saida;
		_tmp35_ = liststore_masa_s;
		_tmp36_ = self->priv->lista_box_masa;
		_tmp36__length1 = self->priv->lista_box_masa_length1;
		main_criar_liststore_para_combobox (self, _tmp34_, _tmp35_, _tmp36_, _tmp36__length1);
		_tmp37_ = self->priv->box_fuerza_entrada;
		_tmp38_ = liststore_fuerza_e;
		_tmp39_ = self->priv->lista_box_fuerza;
		_tmp39__length1 = self->priv->lista_box_fuerza_length1;
		main_criar_liststore_para_combobox (self, _tmp37_, _tmp38_, _tmp39_, _tmp39__length1);
		_tmp40_ = self->priv->box_fuerza_saida;
		_tmp41_ = liststore_fuerza_s;
		_tmp42_ = self->priv->lista_box_fuerza;
		_tmp42__length1 = self->priv->lista_box_fuerza_length1;
		main_criar_liststore_para_combobox (self, _tmp40_, _tmp41_, _tmp42_, _tmp42__length1);
		_tmp43_ = self->priv->box_densidad_entrada;
		_tmp44_ = liststore_densidad_e;
		_tmp45_ = self->priv->lista_box_densidad;
		_tmp45__length1 = self->priv->lista_box_densidad_length1;
		main_criar_liststore_para_combobox (self, _tmp43_, _tmp44_, _tmp45_, _tmp45__length1);
		_tmp46_ = self->priv->box_densidad_saida;
		_tmp47_ = liststore_densidad_s;
		_tmp48_ = self->priv->lista_box_densidad;
		_tmp48__length1 = self->priv->lista_box_densidad_length1;
		main_criar_liststore_para_combobox (self, _tmp46_, _tmp47_, _tmp48_, _tmp48__length1);
		_tmp49_ = self->priv->box_velocidad_entrada;
		_tmp50_ = liststore_velocidad_e;
		_tmp51_ = self->priv->lista_box_velocidad;
		_tmp51__length1 = self->priv->lista_box_velocidad_length1;
		main_criar_liststore_para_combobox (self, _tmp49_, _tmp50_, _tmp51_, _tmp51__length1);
		_tmp52_ = self->priv->box_velocidad_saida;
		_tmp53_ = liststore_velocidad_s;
		_tmp54_ = self->priv->lista_box_velocidad;
		_tmp54__length1 = self->priv->lista_box_velocidad_length1;
		main_criar_liststore_para_combobox (self, _tmp52_, _tmp53_, _tmp54_, _tmp54__length1);
		_tmp55_ = self->priv->box_longitud_entrada;
		_tmp56_ = liststore_longitud_e;
		_tmp57_ = self->priv->lista_box_longitud;
		_tmp57__length1 = self->priv->lista_box_longitud_length1;
		main_criar_liststore_para_combobox (self, _tmp55_, _tmp56_, _tmp57_, _tmp57__length1);
		_tmp58_ = self->priv->box_longitud_saida;
		_tmp59_ = liststore_longitud_s;
		_tmp60_ = self->priv->lista_box_longitud;
		_tmp60__length1 = self->priv->lista_box_longitud_length1;
		main_criar_liststore_para_combobox (self, _tmp58_, _tmp59_, _tmp60_, _tmp60__length1);
		_tmp61_ = self->priv->box_tiempo_entrada;
		_tmp62_ = liststore_tiempo_e;
		_tmp63_ = self->priv->lista_box_tiempo;
		_tmp63__length1 = self->priv->lista_box_tiempo_length1;
		main_criar_liststore_para_combobox (self, _tmp61_, _tmp62_, _tmp63_, _tmp63__length1);
		_tmp64_ = self->priv->box_tiempo_saida;
		_tmp65_ = liststore_tiempo_s;
		_tmp66_ = self->priv->lista_box_tiempo;
		_tmp66__length1 = self->priv->lista_box_tiempo_length1;
		main_criar_liststore_para_combobox (self, _tmp64_, _tmp65_, _tmp66_, _tmp66__length1);
		_tmp67_ = self->priv->box_area_entrada;
		_tmp68_ = liststore_area_e;
		_tmp69_ = self->priv->lista_box_area;
		_tmp69__length1 = self->priv->lista_box_area_length1;
		main_criar_liststore_para_combobox (self, _tmp67_, _tmp68_, _tmp69_, _tmp69__length1);
		_tmp70_ = self->priv->box_area_saida;
		_tmp71_ = liststore_area_s;
		_tmp72_ = self->priv->lista_box_area;
		_tmp72__length1 = self->priv->lista_box_area_length1;
		main_criar_liststore_para_combobox (self, _tmp70_, _tmp71_, _tmp72_, _tmp72__length1);
		_tmp73_ = gtk_builder_get_object (builder, "window");
		_tmp74_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp73_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp73_) : NULL);
		window = _tmp74_;
		_tmp75_ = gtk_builder_get_object (builder, "about_dialog");
		_tmp76_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp75_, gtk_about_dialog_get_type ()) ? ((GtkAboutDialog*) _tmp75_) : NULL);
		_g_object_unref0 (self->priv->dialog);
		self->priv->dialog = _tmp76_;
		_tmp77_ = window;
		gtk_widget_show_all ((GtkWidget*) _tmp77_);
		_g_object_unref0 (window);
		_g_object_unref0 (liststore_tiempo_s);
		_g_object_unref0 (liststore_tiempo_e);
		_g_object_unref0 (liststore_longitud_s);
		_g_object_unref0 (liststore_longitud_e);
		_g_object_unref0 (liststore_area_s);
		_g_object_unref0 (liststore_area_e);
		_g_object_unref0 (liststore_velocidad_s);
		_g_object_unref0 (liststore_velocidad_e);
		_g_object_unref0 (liststore_densidad_s);
		_g_object_unref0 (liststore_densidad_e);
		_g_object_unref0 (liststore_masa_s);
		_g_object_unref0 (liststore_masa_e);
		_g_object_unref0 (liststore_volumen_s);
		_g_object_unref0 (liststore_volumen_e);
		_g_object_unref0 (liststore_fuerza_s);
		_g_object_unref0 (liststore_fuerza_e);
		_g_object_unref0 (liststore_presion_s);
		_g_object_unref0 (liststore_presion_e);
		_g_object_unref0 (builder);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp78_ = NULL;
		GError* _tmp79_ = NULL;
		const gchar* _tmp80_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp78_ = stderr;
		_tmp79_ = e;
		_tmp80_ = _tmp79_->message;
		fprintf (_tmp78_, "Could not load UI: %s\n", _tmp80_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


void main_on_destroy (GtkWidget* window, Main* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	gtk_main_quit ();
}


void main_on_dialog_close_clicked (GtkWidget* window, Main* self) {
	GtkAboutDialog* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->dialog;
	gtk_widget_hide ((GtkWidget*) _tmp0_);
}


void main_on_acerca (GtkWidget* window, Main* self) {
	GtkAboutDialog* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->dialog;
	gtk_window_present ((GtkWindow*) _tmp0_);
}


static void main_criar_liststore_para_combobox (Main* self, GtkComboBox* box, GtkListStore* liststore, gchar** lista, int lista_length1) {
	GtkComboBox* _tmp11_ = NULL;
	GtkListStore* _tmp12_ = NULL;
	GtkCellRendererText* cell = NULL;
	GtkCellRendererText* _tmp13_ = NULL;
	GtkComboBox* _tmp14_ = NULL;
	GtkComboBox* _tmp15_ = NULL;
	GtkComboBox* _tmp16_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (box != NULL);
	g_return_if_fail (liststore != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gchar** _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				GtkTreeIter iter = {0};
				GtkListStore* _tmp4_ = NULL;
				GtkTreeIter _tmp5_ = {0};
				GtkListStore* _tmp6_ = NULL;
				GtkTreeIter _tmp7_ = {0};
				gchar** _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				const gchar* _tmp10_ = NULL;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = lista;
				_tmp3__length1 = lista_length1;
				if (!(_tmp2_ < _tmp3__length1)) {
					break;
				}
				_tmp4_ = liststore;
				gtk_list_store_append (_tmp4_, &_tmp5_);
				iter = _tmp5_;
				_tmp6_ = liststore;
				_tmp7_ = iter;
				_tmp8_ = lista;
				_tmp8__length1 = lista_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				gtk_list_store_set (_tmp6_, &_tmp7_, MAIN_COLUMN_Presion_enum, _tmp10_, -1);
			}
		}
	}
	_tmp11_ = box;
	_tmp12_ = liststore;
	gtk_combo_box_set_model (_tmp11_, (GtkTreeModel*) _tmp12_);
	_tmp13_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp13_);
	cell = _tmp13_;
	_tmp14_ = box;
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp14_, (GtkCellRenderer*) cell, FALSE);
	_tmp15_ = box;
	gtk_cell_layout_set_attributes ((GtkCellLayout*) _tmp15_, (GtkCellRenderer*) cell, "text", MAIN_COLUMN_Presion_enum, NULL);
	_tmp16_ = box;
	gtk_combo_box_set_active (_tmp16_, 0);
	_g_object_unref0 (cell);
}


static void main_get_variables (Main* self, GtkBuilder* builder) {
	GtkBuilder* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GtkSpinButton* _tmp2_ = NULL;
	GtkBuilder* _tmp3_ = NULL;
	GObject* _tmp4_ = NULL;
	GtkSpinButton* _tmp5_ = NULL;
	GtkBuilder* _tmp6_ = NULL;
	GObject* _tmp7_ = NULL;
	GtkSpinButton* _tmp8_ = NULL;
	GtkBuilder* _tmp9_ = NULL;
	GObject* _tmp10_ = NULL;
	GtkSpinButton* _tmp11_ = NULL;
	GtkBuilder* _tmp12_ = NULL;
	GObject* _tmp13_ = NULL;
	GtkSpinButton* _tmp14_ = NULL;
	GtkBuilder* _tmp15_ = NULL;
	GObject* _tmp16_ = NULL;
	GtkSpinButton* _tmp17_ = NULL;
	GtkBuilder* _tmp18_ = NULL;
	GObject* _tmp19_ = NULL;
	GtkSpinButton* _tmp20_ = NULL;
	GtkBuilder* _tmp21_ = NULL;
	GObject* _tmp22_ = NULL;
	GtkSpinButton* _tmp23_ = NULL;
	GtkBuilder* _tmp24_ = NULL;
	GObject* _tmp25_ = NULL;
	GtkSpinButton* _tmp26_ = NULL;
	GtkBuilder* _tmp27_ = NULL;
	GObject* _tmp28_ = NULL;
	GtkEntry* _tmp29_ = NULL;
	GtkBuilder* _tmp30_ = NULL;
	GObject* _tmp31_ = NULL;
	GtkEntry* _tmp32_ = NULL;
	GtkBuilder* _tmp33_ = NULL;
	GObject* _tmp34_ = NULL;
	GtkEntry* _tmp35_ = NULL;
	GtkBuilder* _tmp36_ = NULL;
	GObject* _tmp37_ = NULL;
	GtkEntry* _tmp38_ = NULL;
	GtkBuilder* _tmp39_ = NULL;
	GObject* _tmp40_ = NULL;
	GtkEntry* _tmp41_ = NULL;
	GtkBuilder* _tmp42_ = NULL;
	GObject* _tmp43_ = NULL;
	GtkEntry* _tmp44_ = NULL;
	GtkBuilder* _tmp45_ = NULL;
	GObject* _tmp46_ = NULL;
	GtkEntry* _tmp47_ = NULL;
	GtkBuilder* _tmp48_ = NULL;
	GObject* _tmp49_ = NULL;
	GtkEntry* _tmp50_ = NULL;
	GtkBuilder* _tmp51_ = NULL;
	GObject* _tmp52_ = NULL;
	GtkEntry* _tmp53_ = NULL;
	GtkBuilder* _tmp54_ = NULL;
	GObject* _tmp55_ = NULL;
	GtkEntry* _tmp56_ = NULL;
	GtkBuilder* _tmp57_ = NULL;
	GObject* _tmp58_ = NULL;
	GtkEntry* _tmp59_ = NULL;
	GtkBuilder* _tmp60_ = NULL;
	GObject* _tmp61_ = NULL;
	GtkEntry* _tmp62_ = NULL;
	GtkBuilder* _tmp63_ = NULL;
	GObject* _tmp64_ = NULL;
	GtkEntry* _tmp65_ = NULL;
	GtkBuilder* _tmp66_ = NULL;
	GObject* _tmp67_ = NULL;
	GtkEntry* _tmp68_ = NULL;
	GtkBuilder* _tmp69_ = NULL;
	GObject* _tmp70_ = NULL;
	GtkEntry* _tmp71_ = NULL;
	GtkBuilder* _tmp72_ = NULL;
	GObject* _tmp73_ = NULL;
	GtkEntry* _tmp74_ = NULL;
	GtkBuilder* _tmp75_ = NULL;
	GObject* _tmp76_ = NULL;
	GtkEntry* _tmp77_ = NULL;
	GtkBuilder* _tmp78_ = NULL;
	GObject* _tmp79_ = NULL;
	GtkEntry* _tmp80_ = NULL;
	GtkBuilder* _tmp81_ = NULL;
	GObject* _tmp82_ = NULL;
	GtkComboBox* _tmp83_ = NULL;
	GtkBuilder* _tmp84_ = NULL;
	GObject* _tmp85_ = NULL;
	GtkComboBox* _tmp86_ = NULL;
	GtkBuilder* _tmp87_ = NULL;
	GObject* _tmp88_ = NULL;
	GtkComboBox* _tmp89_ = NULL;
	GtkBuilder* _tmp90_ = NULL;
	GObject* _tmp91_ = NULL;
	GtkComboBox* _tmp92_ = NULL;
	GtkBuilder* _tmp93_ = NULL;
	GObject* _tmp94_ = NULL;
	GtkComboBox* _tmp95_ = NULL;
	GtkBuilder* _tmp96_ = NULL;
	GObject* _tmp97_ = NULL;
	GtkComboBox* _tmp98_ = NULL;
	GtkBuilder* _tmp99_ = NULL;
	GObject* _tmp100_ = NULL;
	GtkComboBox* _tmp101_ = NULL;
	GtkBuilder* _tmp102_ = NULL;
	GObject* _tmp103_ = NULL;
	GtkComboBox* _tmp104_ = NULL;
	GtkBuilder* _tmp105_ = NULL;
	GObject* _tmp106_ = NULL;
	GtkComboBox* _tmp107_ = NULL;
	GtkBuilder* _tmp108_ = NULL;
	GObject* _tmp109_ = NULL;
	GtkComboBox* _tmp110_ = NULL;
	GtkBuilder* _tmp111_ = NULL;
	GObject* _tmp112_ = NULL;
	GtkComboBox* _tmp113_ = NULL;
	GtkBuilder* _tmp114_ = NULL;
	GObject* _tmp115_ = NULL;
	GtkComboBox* _tmp116_ = NULL;
	GtkBuilder* _tmp117_ = NULL;
	GObject* _tmp118_ = NULL;
	GtkComboBox* _tmp119_ = NULL;
	GtkBuilder* _tmp120_ = NULL;
	GObject* _tmp121_ = NULL;
	GtkComboBox* _tmp122_ = NULL;
	GtkBuilder* _tmp123_ = NULL;
	GObject* _tmp124_ = NULL;
	GtkComboBox* _tmp125_ = NULL;
	GtkBuilder* _tmp126_ = NULL;
	GObject* _tmp127_ = NULL;
	GtkComboBox* _tmp128_ = NULL;
	GtkBuilder* _tmp129_ = NULL;
	GObject* _tmp130_ = NULL;
	GtkComboBox* _tmp131_ = NULL;
	GtkBuilder* _tmp132_ = NULL;
	GObject* _tmp133_ = NULL;
	GtkComboBox* _tmp134_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (builder != NULL);
	_tmp0_ = builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "spin_masa");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp1_) : NULL);
	_g_object_unref0 (self->priv->spin_masa);
	self->priv->spin_masa = _tmp2_;
	_tmp3_ = builder;
	_tmp4_ = gtk_builder_get_object (_tmp3_, "spin_area");
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp4_) : NULL);
	_g_object_unref0 (self->priv->spin_area);
	self->priv->spin_area = _tmp5_;
	_tmp6_ = builder;
	_tmp7_ = gtk_builder_get_object (_tmp6_, "spin_presion");
	_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp7_) : NULL);
	_g_object_unref0 (self->priv->spin_presion);
	self->priv->spin_presion = _tmp8_;
	_tmp9_ = builder;
	_tmp10_ = gtk_builder_get_object (_tmp9_, "spin_volumen");
	_tmp11_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp10_) : NULL);
	_g_object_unref0 (self->priv->spin_volumen);
	self->priv->spin_volumen = _tmp11_;
	_tmp12_ = builder;
	_tmp13_ = gtk_builder_get_object (_tmp12_, "spin_velocidad");
	_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp13_) : NULL);
	_g_object_unref0 (self->priv->spin_velocidad);
	self->priv->spin_velocidad = _tmp14_;
	_tmp15_ = builder;
	_tmp16_ = gtk_builder_get_object (_tmp15_, "spin_fuerza");
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp16_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp16_) : NULL);
	_g_object_unref0 (self->priv->spin_fuerza);
	self->priv->spin_fuerza = _tmp17_;
	_tmp18_ = builder;
	_tmp19_ = gtk_builder_get_object (_tmp18_, "spin_densidad");
	_tmp20_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp19_) : NULL);
	_g_object_unref0 (self->priv->spin_densidad);
	self->priv->spin_densidad = _tmp20_;
	_tmp21_ = builder;
	_tmp22_ = gtk_builder_get_object (_tmp21_, "spin_longitud");
	_tmp23_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp22_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp22_) : NULL);
	_g_object_unref0 (self->priv->spin_longitud);
	self->priv->spin_longitud = _tmp23_;
	_tmp24_ = builder;
	_tmp25_ = gtk_builder_get_object (_tmp24_, "spin_tiempo");
	_tmp26_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp25_, gtk_spin_button_get_type ()) ? ((GtkSpinButton*) _tmp25_) : NULL);
	_g_object_unref0 (self->priv->spin_tiempo);
	self->priv->spin_tiempo = _tmp26_;
	_tmp27_ = builder;
	_tmp28_ = gtk_builder_get_object (_tmp27_, "entry_area_entrada");
	_tmp29_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp28_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp28_) : NULL);
	_g_object_unref0 (self->priv->entry_area_entrada);
	self->priv->entry_area_entrada = _tmp29_;
	_tmp30_ = builder;
	_tmp31_ = gtk_builder_get_object (_tmp30_, "entry_area_saida");
	_tmp32_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp31_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp31_) : NULL);
	_g_object_unref0 (self->priv->entry_area_saida);
	self->priv->entry_area_saida = _tmp32_;
	_tmp33_ = builder;
	_tmp34_ = gtk_builder_get_object (_tmp33_, "entry_masa_entrada");
	_tmp35_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp34_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp34_) : NULL);
	_g_object_unref0 (self->priv->entry_masa_entrada);
	self->priv->entry_masa_entrada = _tmp35_;
	_tmp36_ = builder;
	_tmp37_ = gtk_builder_get_object (_tmp36_, "entry_masa_saida");
	_tmp38_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp37_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp37_) : NULL);
	_g_object_unref0 (self->priv->entry_masa_saida);
	self->priv->entry_masa_saida = _tmp38_;
	_tmp39_ = builder;
	_tmp40_ = gtk_builder_get_object (_tmp39_, "entry_presion_entrada");
	_tmp41_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp40_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp40_) : NULL);
	_g_object_unref0 (self->priv->entry_presion_entrada);
	self->priv->entry_presion_entrada = _tmp41_;
	_tmp42_ = builder;
	_tmp43_ = gtk_builder_get_object (_tmp42_, "entry_presion_saida");
	_tmp44_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp43_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp43_) : NULL);
	_g_object_unref0 (self->priv->entry_presion_saida);
	self->priv->entry_presion_saida = _tmp44_;
	_tmp45_ = builder;
	_tmp46_ = gtk_builder_get_object (_tmp45_, "entry_volumen_entrada");
	_tmp47_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp46_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp46_) : NULL);
	_g_object_unref0 (self->priv->entry_volumen_entrada);
	self->priv->entry_volumen_entrada = _tmp47_;
	_tmp48_ = builder;
	_tmp49_ = gtk_builder_get_object (_tmp48_, "entry_volumen_saida");
	_tmp50_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp49_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp49_) : NULL);
	_g_object_unref0 (self->priv->entry_volumen_saida);
	self->priv->entry_volumen_saida = _tmp50_;
	_tmp51_ = builder;
	_tmp52_ = gtk_builder_get_object (_tmp51_, "entry_fuerza_entrada");
	_tmp53_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp52_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp52_) : NULL);
	_g_object_unref0 (self->priv->entry_fuerza_entrada);
	self->priv->entry_fuerza_entrada = _tmp53_;
	_tmp54_ = builder;
	_tmp55_ = gtk_builder_get_object (_tmp54_, "entry_fuerza_saida");
	_tmp56_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp55_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp55_) : NULL);
	_g_object_unref0 (self->priv->entry_fuerza_saida);
	self->priv->entry_fuerza_saida = _tmp56_;
	_tmp57_ = builder;
	_tmp58_ = gtk_builder_get_object (_tmp57_, "entry_densidad_entrada");
	_tmp59_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp58_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp58_) : NULL);
	_g_object_unref0 (self->priv->entry_densidad_entrada);
	self->priv->entry_densidad_entrada = _tmp59_;
	_tmp60_ = builder;
	_tmp61_ = gtk_builder_get_object (_tmp60_, "entry_densidad_saida");
	_tmp62_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp61_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp61_) : NULL);
	_g_object_unref0 (self->priv->entry_densidad_saida);
	self->priv->entry_densidad_saida = _tmp62_;
	_tmp63_ = builder;
	_tmp64_ = gtk_builder_get_object (_tmp63_, "entry_velocidad_entrada");
	_tmp65_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp64_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp64_) : NULL);
	_g_object_unref0 (self->priv->entry_velocidad_entrada);
	self->priv->entry_velocidad_entrada = _tmp65_;
	_tmp66_ = builder;
	_tmp67_ = gtk_builder_get_object (_tmp66_, "entry_velocidad_saida");
	_tmp68_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp67_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp67_) : NULL);
	_g_object_unref0 (self->priv->entry_velocidad_saida);
	self->priv->entry_velocidad_saida = _tmp68_;
	_tmp69_ = builder;
	_tmp70_ = gtk_builder_get_object (_tmp69_, "entry_longitud_entrada");
	_tmp71_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp70_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp70_) : NULL);
	_g_object_unref0 (self->priv->entry_longitud_entrada);
	self->priv->entry_longitud_entrada = _tmp71_;
	_tmp72_ = builder;
	_tmp73_ = gtk_builder_get_object (_tmp72_, "entry_longitud_saida");
	_tmp74_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp73_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp73_) : NULL);
	_g_object_unref0 (self->priv->entry_longitud_saida);
	self->priv->entry_longitud_saida = _tmp74_;
	_tmp75_ = builder;
	_tmp76_ = gtk_builder_get_object (_tmp75_, "entry_tiempo_entrada");
	_tmp77_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp76_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp76_) : NULL);
	_g_object_unref0 (self->priv->entry_tiempo_entrada);
	self->priv->entry_tiempo_entrada = _tmp77_;
	_tmp78_ = builder;
	_tmp79_ = gtk_builder_get_object (_tmp78_, "entry_tiempo_saida");
	_tmp80_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp79_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp79_) : NULL);
	_g_object_unref0 (self->priv->entry_tiempo_saida);
	self->priv->entry_tiempo_saida = _tmp80_;
	_tmp81_ = builder;
	_tmp82_ = gtk_builder_get_object (_tmp81_, "box_presion_entrada");
	_tmp83_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp82_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp82_) : NULL);
	_g_object_unref0 (self->priv->box_presion_entrada);
	self->priv->box_presion_entrada = _tmp83_;
	_tmp84_ = builder;
	_tmp85_ = gtk_builder_get_object (_tmp84_, "box_presion_saida");
	_tmp86_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp85_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp85_) : NULL);
	_g_object_unref0 (self->priv->box_presion_saida);
	self->priv->box_presion_saida = _tmp86_;
	_tmp87_ = builder;
	_tmp88_ = gtk_builder_get_object (_tmp87_, "box_volumen_entrada");
	_tmp89_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp88_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp88_) : NULL);
	_g_object_unref0 (self->priv->box_volumen_entrada);
	self->priv->box_volumen_entrada = _tmp89_;
	_tmp90_ = builder;
	_tmp91_ = gtk_builder_get_object (_tmp90_, "box_volumen_saida");
	_tmp92_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp91_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp91_) : NULL);
	_g_object_unref0 (self->priv->box_volumen_saida);
	self->priv->box_volumen_saida = _tmp92_;
	_tmp93_ = builder;
	_tmp94_ = gtk_builder_get_object (_tmp93_, "box_fuerza_entrada");
	_tmp95_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp94_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp94_) : NULL);
	_g_object_unref0 (self->priv->box_fuerza_entrada);
	self->priv->box_fuerza_entrada = _tmp95_;
	_tmp96_ = builder;
	_tmp97_ = gtk_builder_get_object (_tmp96_, "box_fuerza_saida");
	_tmp98_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp97_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp97_) : NULL);
	_g_object_unref0 (self->priv->box_fuerza_saida);
	self->priv->box_fuerza_saida = _tmp98_;
	_tmp99_ = builder;
	_tmp100_ = gtk_builder_get_object (_tmp99_, "box_masa_entrada");
	_tmp101_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp100_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp100_) : NULL);
	_g_object_unref0 (self->priv->box_masa_entrada);
	self->priv->box_masa_entrada = _tmp101_;
	_tmp102_ = builder;
	_tmp103_ = gtk_builder_get_object (_tmp102_, "box_masa_saida");
	_tmp104_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp103_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp103_) : NULL);
	_g_object_unref0 (self->priv->box_masa_saida);
	self->priv->box_masa_saida = _tmp104_;
	_tmp105_ = builder;
	_tmp106_ = gtk_builder_get_object (_tmp105_, "box_densidad_entrada");
	_tmp107_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp106_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp106_) : NULL);
	_g_object_unref0 (self->priv->box_densidad_entrada);
	self->priv->box_densidad_entrada = _tmp107_;
	_tmp108_ = builder;
	_tmp109_ = gtk_builder_get_object (_tmp108_, "box_densidad_saida");
	_tmp110_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp109_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp109_) : NULL);
	_g_object_unref0 (self->priv->box_densidad_saida);
	self->priv->box_densidad_saida = _tmp110_;
	_tmp111_ = builder;
	_tmp112_ = gtk_builder_get_object (_tmp111_, "box_velocidad_entrada");
	_tmp113_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp112_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp112_) : NULL);
	_g_object_unref0 (self->priv->box_velocidad_entrada);
	self->priv->box_velocidad_entrada = _tmp113_;
	_tmp114_ = builder;
	_tmp115_ = gtk_builder_get_object (_tmp114_, "box_velocidad_saida");
	_tmp116_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp115_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp115_) : NULL);
	_g_object_unref0 (self->priv->box_velocidad_saida);
	self->priv->box_velocidad_saida = _tmp116_;
	_tmp117_ = builder;
	_tmp118_ = gtk_builder_get_object (_tmp117_, "box_area_entrada");
	_tmp119_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp118_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp118_) : NULL);
	_g_object_unref0 (self->priv->box_area_entrada);
	self->priv->box_area_entrada = _tmp119_;
	_tmp120_ = builder;
	_tmp121_ = gtk_builder_get_object (_tmp120_, "box_area_saida");
	_tmp122_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp121_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp121_) : NULL);
	_g_object_unref0 (self->priv->box_area_saida);
	self->priv->box_area_saida = _tmp122_;
	_tmp123_ = builder;
	_tmp124_ = gtk_builder_get_object (_tmp123_, "box_longitud_entrada");
	_tmp125_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp124_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp124_) : NULL);
	_g_object_unref0 (self->priv->box_longitud_entrada);
	self->priv->box_longitud_entrada = _tmp125_;
	_tmp126_ = builder;
	_tmp127_ = gtk_builder_get_object (_tmp126_, "box_longitud_saida");
	_tmp128_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp127_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp127_) : NULL);
	_g_object_unref0 (self->priv->box_longitud_saida);
	self->priv->box_longitud_saida = _tmp128_;
	_tmp129_ = builder;
	_tmp130_ = gtk_builder_get_object (_tmp129_, "box_tiempo_entrada");
	_tmp131_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp130_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp130_) : NULL);
	_g_object_unref0 (self->priv->box_tiempo_entrada);
	self->priv->box_tiempo_entrada = _tmp131_;
	_tmp132_ = builder;
	_tmp133_ = gtk_builder_get_object (_tmp132_, "box_tiempo_saida");
	_tmp134_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp133_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp133_) : NULL);
	_g_object_unref0 (self->priv->box_tiempo_saida);
	self->priv->box_tiempo_saida = _tmp134_;
}


static void main_escribir_entrada (Main* self, GtkSpinButton* spin, gchar** lista, int lista_length1, GtkComboBox* box_entrada, GtkEntry* entry_entrada) {
	gfloat valor = 0.0F;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gchar* string = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	GtkComboBox* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	GtkEntry* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (spin != NULL);
	g_return_if_fail (box_entrada != NULL);
	g_return_if_fail (entry_entrada != NULL);
	_tmp0_ = spin;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	valor = (gfloat) _tmp1_;
	_tmp2_ = g_strdup_printf ("%g", valor);
	string = _tmp2_;
	_tmp3_ = string;
	_tmp4_ = lista;
	_tmp4__length1 = lista_length1;
	_tmp5_ = box_entrada;
	_tmp6_ = gtk_combo_box_get_active (_tmp5_);
	_tmp7_ = _tmp4_[_tmp6_];
	_tmp8_ = g_strconcat ("  ", _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp3_, _tmp9_, NULL);
	_g_free0 (string);
	string = _tmp10_;
	_g_free0 (_tmp9_);
	_tmp11_ = entry_entrada;
	_tmp12_ = string;
	gtk_entry_set_text (_tmp11_, _tmp12_);
	_g_free0 (string);
}


static void main_escribir_saida (Main* self, gdouble aux, GtkSpinButton* spin, gchar** lista, int lista_length1, GtkComboBox* box_saida, GtkEntry* entry_saida) {
	gfloat valor = 0.0F;
	gdouble _tmp0_ = 0.0;
	gchar* string = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	GtkComboBox* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GtkEntry* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (spin != NULL);
	g_return_if_fail (box_saida != NULL);
	g_return_if_fail (entry_saida != NULL);
	_tmp0_ = aux;
	valor = (gfloat) _tmp0_;
	_tmp1_ = g_strdup_printf ("%g", valor);
	string = _tmp1_;
	_tmp2_ = string;
	_tmp3_ = lista;
	_tmp3__length1 = lista_length1;
	_tmp4_ = box_saida;
	_tmp5_ = gtk_combo_box_get_active (_tmp4_);
	_tmp6_ = _tmp3_[_tmp5_];
	_tmp7_ = g_strconcat ("  ", _tmp6_, NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strconcat (_tmp2_, _tmp8_, NULL);
	_g_free0 (string);
	string = _tmp9_;
	_g_free0 (_tmp8_);
	_tmp10_ = entry_saida;
	_tmp11_ = string;
	gtk_entry_set_text (_tmp10_, _tmp11_);
	_g_free0 (string);
}


void main_on_but_aplicar_presion_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp64_ = NULL;
	gchar** _tmp65_ = NULL;
	gint _tmp65__length1 = 0;
	GtkComboBox* _tmp66_ = NULL;
	GtkEntry* _tmp67_ = NULL;
	gdouble _tmp68_ = 0.0;
	GtkSpinButton* _tmp69_ = NULL;
	gchar** _tmp70_ = NULL;
	gint _tmp70__length1 = 0;
	GtkComboBox* _tmp71_ = NULL;
	GtkEntry* _tmp72_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_presion;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_presion_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_presion_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					gdouble _tmp7_ = 0.0;
					_tmp6_ = aux;
					_tmp7_ = pow ((gdouble) 10, (gdouble) 6);
					aux = _tmp6_ * _tmp7_;
					break;
				}
				case 2:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 10;
					break;
				}
				case 3:
				{
					gdouble _tmp9_ = 0.0;
					_tmp9_ = aux;
					aux = _tmp9_ * 9.87;
					break;
				}
				case 4:
				{
					gdouble _tmp10_ = 0.0;
					_tmp10_ = aux;
					aux = _tmp10_ * 10.2;
					break;
				}
				case 5:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 101971.6;
					break;
				}
				case 6:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 7500.64;
					break;
				}
				default:
				{
					aux = (gdouble) 0;
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp13_ = NULL;
			gint _tmp14_ = 0;
			_tmp13_ = self->priv->box_presion_saida;
			_tmp14_ = gtk_combo_box_get_active (_tmp13_);
			switch (_tmp14_) {
				case 0:
				{
					gdouble _tmp15_ = 0.0;
					gdouble _tmp16_ = 0.0;
					_tmp15_ = aux;
					_tmp16_ = pow ((gdouble) 10, (gdouble) -6);
					aux = _tmp15_ * _tmp16_;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp17_ = 0.0;
					gdouble _tmp18_ = 0.0;
					_tmp17_ = aux;
					_tmp18_ = pow ((gdouble) 10, (gdouble) -5);
					aux = _tmp17_ * _tmp18_;
					break;
				}
				case 3:
				{
					gdouble _tmp19_ = 0.0;
					gdouble _tmp20_ = 0.0;
					_tmp19_ = aux;
					_tmp20_ = pow ((gdouble) 10, (gdouble) -6);
					aux = _tmp19_ * (9.87 * _tmp20_);
					break;
				}
				case 4:
				{
					gdouble _tmp21_ = 0.0;
					_tmp21_ = aux;
					aux = _tmp21_ * 0.0000101972;
					break;
				}
				case 5:
				{
					gdouble _tmp22_ = 0.0;
					_tmp22_ = aux;
					aux = _tmp22_ * 0.101972;
					break;
				}
				case 6:
				{
					gdouble _tmp23_ = 0.0;
					_tmp23_ = aux;
					aux = _tmp23_ * 0.00750064;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp24_ = NULL;
			gint _tmp25_ = 0;
			_tmp24_ = self->priv->box_presion_saida;
			_tmp25_ = gtk_combo_box_get_active (_tmp24_);
			switch (_tmp25_) {
				case 0:
				{
					gdouble _tmp26_ = 0.0;
					_tmp26_ = aux;
					aux = _tmp26_ * 0.101325;
					break;
				}
				case 1:
				{
					gdouble _tmp27_ = 0.0;
					_tmp27_ = aux;
					aux = _tmp27_ * 100000;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp28_ = 0.0;
					_tmp28_ = aux;
					aux = _tmp28_ * 0.986923;
					break;
				}
				case 4:
				{
					gdouble _tmp29_ = 0.0;
					_tmp29_ = aux;
					aux = _tmp29_ * 1.0197;
					break;
				}
				case 5:
				{
					gdouble _tmp30_ = 0.0;
					_tmp30_ = aux;
					aux = _tmp30_ * 10197.16;
					break;
				}
				case 6:
				{
					gdouble _tmp31_ = 0.0;
					_tmp31_ = aux;
					aux = _tmp31_ * 750.06;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp32_ = NULL;
			gint _tmp33_ = 0;
			_tmp32_ = self->priv->box_presion_saida;
			_tmp33_ = gtk_combo_box_get_active (_tmp32_);
			switch (_tmp33_) {
				case 0:
				{
					gdouble _tmp34_ = 0.0;
					_tmp34_ = aux;
					aux = _tmp34_ * 0.101325;
					break;
				}
				case 1:
				{
					gdouble _tmp35_ = 0.0;
					_tmp35_ = aux;
					aux = _tmp35_ * 101325;
					break;
				}
				case 2:
				{
					gdouble _tmp36_ = 0.0;
					_tmp36_ = aux;
					aux = _tmp36_ * 1.0132;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					gdouble _tmp37_ = 0.0;
					_tmp37_ = aux;
					aux = _tmp37_ * 1.0332;
					break;
				}
				case 5:
				{
					gdouble _tmp38_ = 0.0;
					_tmp38_ = aux;
					aux = _tmp38_ * 10332.27;
					break;
				}
				case 6:
				{
					gdouble _tmp39_ = 0.0;
					_tmp39_ = aux;
					aux = _tmp39_ * 760;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 4:
		{
			GtkComboBox* _tmp40_ = NULL;
			gint _tmp41_ = 0;
			_tmp40_ = self->priv->box_presion_saida;
			_tmp41_ = gtk_combo_box_get_active (_tmp40_);
			switch (_tmp41_) {
				case 0:
				{
					gdouble _tmp42_ = 0.0;
					_tmp42_ = aux;
					aux = _tmp42_ * 0.098067;
					break;
				}
				case 1:
				{
					gdouble _tmp43_ = 0.0;
					_tmp43_ = aux;
					aux = _tmp43_ * 98066.52;
					break;
				}
				case 2:
				{
					gdouble _tmp44_ = 0.0;
					_tmp44_ = aux;
					aux = _tmp44_ * 0.980665;
					break;
				}
				case 3:
				{
					gdouble _tmp45_ = 0.0;
					_tmp45_ = aux;
					aux = _tmp45_ * 0.967841;
					break;
				}
				case 4:
				{
					break;
				}
				case 5:
				{
					gdouble _tmp46_ = 0.0;
					_tmp46_ = aux;
					aux = _tmp46_ * 10000;
					break;
				}
				case 6:
				{
					gdouble _tmp47_ = 0.0;
					_tmp47_ = aux;
					aux = _tmp47_ * 735.56;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 5:
		{
			GtkComboBox* _tmp48_ = NULL;
			gint _tmp49_ = 0;
			_tmp48_ = self->priv->box_presion_saida;
			_tmp49_ = gtk_combo_box_get_active (_tmp48_);
			switch (_tmp49_) {
				case 0:
				{
					gdouble _tmp50_ = 0.0;
					_tmp50_ = aux;
					aux = _tmp50_ * 0.0000098067;
					break;
				}
				case 1:
				{
					gdouble _tmp51_ = 0.0;
					_tmp51_ = aux;
					aux = _tmp51_ * 9.8067;
					break;
				}
				case 2:
				{
					gdouble _tmp52_ = 0.0;
					_tmp52_ = aux;
					aux = _tmp52_ * 0.0000980665;
					break;
				}
				case 3:
				{
					gdouble _tmp53_ = 0.0;
					_tmp53_ = aux;
					aux = _tmp53_ * 0.0000967841;
					break;
				}
				case 4:
				{
					gdouble _tmp54_ = 0.0;
					_tmp54_ = aux;
					aux = _tmp54_ * 0.0001;
					break;
				}
				case 5:
				{
					break;
				}
				case 6:
				{
					gdouble _tmp55_ = 0.0;
					_tmp55_ = aux;
					aux = _tmp55_ * 0.073556;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 6:
		{
			GtkComboBox* _tmp56_ = NULL;
			gint _tmp57_ = 0;
			_tmp56_ = self->priv->box_presion_saida;
			_tmp57_ = gtk_combo_box_get_active (_tmp56_);
			switch (_tmp57_) {
				case 0:
				{
					gdouble _tmp58_ = 0.0;
					_tmp58_ = aux;
					aux = _tmp58_ * 0.00013332;
					break;
				}
				case 1:
				{
					gdouble _tmp59_ = 0.0;
					_tmp59_ = aux;
					aux = _tmp59_ * 133.32;
					break;
				}
				case 2:
				{
					gdouble _tmp60_ = 0.0;
					_tmp60_ = aux;
					aux = _tmp60_ * 0.00133322;
					break;
				}
				case 3:
				{
					gdouble _tmp61_ = 0.0;
					_tmp61_ = aux;
					aux = _tmp61_ * 0.00131579;
					break;
				}
				case 4:
				{
					gdouble _tmp62_ = 0.0;
					_tmp62_ = aux;
					aux = _tmp62_ * 0.00135951;
					break;
				}
				case 5:
				{
					gdouble _tmp63_ = 0.0;
					_tmp63_ = aux;
					aux = _tmp63_ * 13.5951;
					break;
				}
				case 6:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp64_ = self->priv->spin_presion;
	_tmp65_ = self->priv->lista_box_presion;
	_tmp65__length1 = self->priv->lista_box_presion_length1;
	_tmp66_ = self->priv->box_presion_entrada;
	_tmp67_ = self->priv->entry_presion_entrada;
	main_escribir_entrada (self, _tmp64_, _tmp65_, _tmp65__length1, _tmp66_, _tmp67_);
	_tmp68_ = aux;
	_tmp69_ = self->priv->spin_presion;
	_tmp70_ = self->priv->lista_box_presion;
	_tmp70__length1 = self->priv->lista_box_presion_length1;
	_tmp71_ = self->priv->box_presion_saida;
	_tmp72_ = self->priv->entry_presion_saida;
	main_escribir_saida (self, _tmp68_, _tmp69_, _tmp70_, _tmp70__length1, _tmp71_, _tmp72_);
}


void main_on_but_aplicar_fuerza_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp29_ = NULL;
	gchar** _tmp30_ = NULL;
	gint _tmp30__length1 = 0;
	GtkComboBox* _tmp31_ = NULL;
	GtkEntry* _tmp32_ = NULL;
	gdouble _tmp33_ = 0.0;
	GtkSpinButton* _tmp34_ = NULL;
	gchar** _tmp35_ = NULL;
	gint _tmp35__length1 = 0;
	GtkComboBox* _tmp36_ = NULL;
	GtkEntry* _tmp37_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_fuerza;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_fuerza_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_fuerza_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 0.101972;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 100000;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					break;
				}
				default:
				{
					aux = (gdouble) 0;
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			_tmp8_ = self->priv->box_fuerza_saida;
			_tmp9_ = gtk_combo_box_get_active (_tmp8_);
			switch (_tmp9_) {
				case 0:
				{
					gdouble _tmp10_ = 0.0;
					_tmp10_ = aux;
					aux = _tmp10_ * 9.8066;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 980665;
					break;
				}
				case 3:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 9.8066;
					break;
				}
				case 4:
				{
					gdouble _tmp13_ = 0.0;
					_tmp13_ = aux;
					aux = _tmp13_ * 9.8066;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			_tmp14_ = self->priv->box_fuerza_saida;
			_tmp15_ = gtk_combo_box_get_active (_tmp14_);
			switch (_tmp15_) {
				case 0:
				{
					gdouble _tmp16_ = 0.0;
					_tmp16_ = aux;
					aux = _tmp16_ * 0.00001;
					break;
				}
				case 1:
				{
					gdouble _tmp17_ = 0.0;
					_tmp17_ = aux;
					aux = _tmp17_ * 0.0000010197;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp18_ = 0.0;
					_tmp18_ = aux;
					aux = _tmp18_ * 0.00001;
					break;
				}
				case 4:
				{
					gdouble _tmp19_ = 0.0;
					_tmp19_ = aux;
					aux = _tmp19_ * 0.00001;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp20_ = NULL;
			gint _tmp21_ = 0;
			_tmp20_ = self->priv->box_fuerza_saida;
			_tmp21_ = gtk_combo_box_get_active (_tmp20_);
			switch (_tmp21_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp22_ = 0.0;
					_tmp22_ = aux;
					aux = _tmp22_ * 0.101972;
					break;
				}
				case 2:
				{
					gdouble _tmp23_ = 0.0;
					_tmp23_ = aux;
					aux = _tmp23_ * 100000;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					break;
				}
				default:
				break;
			}
			break;
		}
		case 4:
		{
			GtkComboBox* _tmp24_ = NULL;
			gint _tmp25_ = 0;
			_tmp24_ = self->priv->box_fuerza_saida;
			_tmp25_ = gtk_combo_box_get_active (_tmp24_);
			switch (_tmp25_) {
				case 0:
				{
					gdouble _tmp26_ = 0.0;
					_tmp26_ = aux;
					aux = _tmp26_ * 0.098067;
					break;
				}
				case 1:
				{
					gdouble _tmp27_ = 0.0;
					_tmp27_ = aux;
					aux = _tmp27_ * 0.101972;
					break;
				}
				case 2:
				{
					gdouble _tmp28_ = 0.0;
					_tmp28_ = aux;
					aux = _tmp28_ * 100000;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp29_ = self->priv->spin_fuerza;
	_tmp30_ = self->priv->lista_box_fuerza;
	_tmp30__length1 = self->priv->lista_box_fuerza_length1;
	_tmp31_ = self->priv->box_fuerza_entrada;
	_tmp32_ = self->priv->entry_fuerza_entrada;
	main_escribir_entrada (self, _tmp29_, _tmp30_, _tmp30__length1, _tmp31_, _tmp32_);
	_tmp33_ = aux;
	_tmp34_ = self->priv->spin_fuerza;
	_tmp35_ = self->priv->lista_box_fuerza;
	_tmp35__length1 = self->priv->lista_box_fuerza_length1;
	_tmp36_ = self->priv->box_fuerza_saida;
	_tmp37_ = self->priv->entry_fuerza_saida;
	main_escribir_saida (self, _tmp33_, _tmp34_, _tmp35_, _tmp35__length1, _tmp36_, _tmp37_);
}


void main_on_but_aplicar_volumen_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp36_ = NULL;
	gchar** _tmp37_ = NULL;
	gint _tmp37__length1 = 0;
	GtkComboBox* _tmp38_ = NULL;
	GtkEntry* _tmp39_ = NULL;
	gdouble _tmp40_ = 0.0;
	GtkSpinButton* _tmp41_ = NULL;
	gchar** _tmp42_ = NULL;
	gint _tmp42__length1 = 0;
	GtkComboBox* _tmp43_ = NULL;
	GtkEntry* _tmp44_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_volumen;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_volumen_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_volumen_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 1000000000;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 1000000000000LL;
					break;
				}
				case 3:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 1000000000000LL;
					break;
				}
				case 4:
				{
					gdouble _tmp9_ = 0.0;
					_tmp9_ = aux;
					aux = _tmp9_ * 1000000000000000LL;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			_tmp10_ = self->priv->box_volumen_saida;
			_tmp11_ = gtk_combo_box_get_active (_tmp10_);
			switch (_tmp11_) {
				case 0:
				{
					gdouble _tmp12_ = 0.0;
					gdouble _tmp13_ = 0.0;
					_tmp12_ = aux;
					_tmp13_ = pow ((gdouble) 10, (gdouble) -9);
					aux = _tmp12_ * _tmp13_;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp14_ = 0.0;
					_tmp14_ = aux;
					aux = _tmp14_ * 1000;
					break;
				}
				case 3:
				{
					gdouble _tmp15_ = 0.0;
					_tmp15_ = aux;
					aux = _tmp15_ * 1000;
					break;
				}
				case 4:
				{
					gdouble _tmp16_ = 0.0;
					_tmp16_ = aux;
					aux = _tmp16_ * 1000000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			_tmp17_ = self->priv->box_volumen_saida;
			_tmp18_ = gtk_combo_box_get_active (_tmp17_);
			switch (_tmp18_) {
				case 0:
				{
					gdouble _tmp19_ = 0.0;
					gdouble _tmp20_ = 0.0;
					_tmp19_ = aux;
					_tmp20_ = pow ((gdouble) 10, (gdouble) -12);
					aux = _tmp19_ * _tmp20_;
					break;
				}
				case 1:
				{
					gdouble _tmp21_ = 0.0;
					_tmp21_ = aux;
					aux = _tmp21_ * 0.001;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					gdouble _tmp22_ = 0.0;
					_tmp22_ = aux;
					aux = _tmp22_ * 1000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp23_ = NULL;
			gint _tmp24_ = 0;
			_tmp23_ = self->priv->box_volumen_saida;
			_tmp24_ = gtk_combo_box_get_active (_tmp23_);
			switch (_tmp24_) {
				case 0:
				{
					gdouble _tmp25_ = 0.0;
					gdouble _tmp26_ = 0.0;
					_tmp25_ = aux;
					_tmp26_ = pow ((gdouble) 10, (gdouble) -12);
					aux = _tmp25_ * _tmp26_;
					break;
				}
				case 1:
				{
					gdouble _tmp27_ = 0.0;
					_tmp27_ = aux;
					aux = _tmp27_ * 0.001;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					gdouble _tmp28_ = 0.0;
					_tmp28_ = aux;
					aux = _tmp28_ * 1000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 4:
		{
			GtkComboBox* _tmp29_ = NULL;
			gint _tmp30_ = 0;
			_tmp29_ = self->priv->box_volumen_saida;
			_tmp30_ = gtk_combo_box_get_active (_tmp29_);
			switch (_tmp30_) {
				case 0:
				{
					gdouble _tmp31_ = 0.0;
					gdouble _tmp32_ = 0.0;
					_tmp31_ = aux;
					_tmp32_ = pow ((gdouble) 10, (gdouble) -15);
					aux = _tmp31_ * _tmp32_;
					break;
				}
				case 1:
				{
					gdouble _tmp33_ = 0.0;
					_tmp33_ = aux;
					aux = _tmp33_ * 0.000001;
					break;
				}
				case 2:
				{
					gdouble _tmp34_ = 0.0;
					_tmp34_ = aux;
					aux = _tmp34_ * 0.001;
					break;
				}
				case 3:
				{
					gdouble _tmp35_ = 0.0;
					_tmp35_ = aux;
					aux = _tmp35_ * 0.001;
					break;
				}
				case 4:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp36_ = self->priv->spin_volumen;
	_tmp37_ = self->priv->lista_box_volumen;
	_tmp37__length1 = self->priv->lista_box_volumen_length1;
	_tmp38_ = self->priv->box_volumen_entrada;
	_tmp39_ = self->priv->entry_volumen_entrada;
	main_escribir_entrada (self, _tmp36_, _tmp37_, _tmp37__length1, _tmp38_, _tmp39_);
	_tmp40_ = aux;
	_tmp41_ = self->priv->spin_volumen;
	_tmp42_ = self->priv->lista_box_volumen;
	_tmp42__length1 = self->priv->lista_box_volumen_length1;
	_tmp43_ = self->priv->box_volumen_saida;
	_tmp44_ = self->priv->entry_volumen_saida;
	main_escribir_saida (self, _tmp40_, _tmp41_, _tmp42_, _tmp42__length1, _tmp43_, _tmp44_);
}


void main_on_but_aplicar_masa_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp34_ = NULL;
	gchar** _tmp35_ = NULL;
	gint _tmp35__length1 = 0;
	GtkComboBox* _tmp36_ = NULL;
	GtkEntry* _tmp37_ = NULL;
	gdouble _tmp38_ = 0.0;
	GtkSpinButton* _tmp39_ = NULL;
	gchar** _tmp40_ = NULL;
	gint _tmp40__length1 = 0;
	GtkComboBox* _tmp41_ = NULL;
	GtkEntry* _tmp42_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_masa;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_masa_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_masa_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 9.8067;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 1000;
					break;
				}
				case 3:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 10000;
					break;
				}
				case 4:
				{
					gdouble _tmp9_ = 0.0;
					_tmp9_ = aux;
					aux = _tmp9_ * 1000000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			_tmp10_ = self->priv->box_masa_saida;
			_tmp11_ = gtk_combo_box_get_active (_tmp10_);
			switch (_tmp11_) {
				case 0:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 0.101972;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp13_ = 0.0;
					_tmp13_ = aux;
					aux = _tmp13_ * 101.97;
					break;
				}
				case 3:
				{
					gdouble _tmp14_ = 0.0;
					_tmp14_ = aux;
					aux = _tmp14_ * 1019.72;
					break;
				}
				case 4:
				{
					gdouble _tmp15_ = 0.0;
					_tmp15_ = aux;
					aux = _tmp15_ * 101971.6;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp16_ = NULL;
			gint _tmp17_ = 0;
			_tmp16_ = self->priv->box_masa_saida;
			_tmp17_ = gtk_combo_box_get_active (_tmp16_);
			switch (_tmp17_) {
				case 0:
				{
					gdouble _tmp18_ = 0.0;
					_tmp18_ = aux;
					aux = _tmp18_ * 0.001;
					break;
				}
				case 1:
				{
					gdouble _tmp19_ = 0.0;
					_tmp19_ = aux;
					aux = _tmp19_ * 0.00980665;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp20_ = 0.0;
					_tmp20_ = aux;
					aux = _tmp20_ * 10;
					break;
				}
				case 4:
				{
					gdouble _tmp21_ = 0.0;
					_tmp21_ = aux;
					aux = _tmp21_ * 1000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp22_ = NULL;
			gint _tmp23_ = 0;
			_tmp22_ = self->priv->box_masa_saida;
			_tmp23_ = gtk_combo_box_get_active (_tmp22_);
			switch (_tmp23_) {
				case 0:
				{
					gdouble _tmp24_ = 0.0;
					_tmp24_ = aux;
					aux = _tmp24_ * 0.0001;
					break;
				}
				case 1:
				{
					gdouble _tmp25_ = 0.0;
					_tmp25_ = aux;
					aux = _tmp25_ * 0.00098067;
					break;
				}
				case 2:
				{
					gdouble _tmp26_ = 0.0;
					_tmp26_ = aux;
					aux = _tmp26_ * 0.1;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					gdouble _tmp27_ = 0.0;
					_tmp27_ = aux;
					aux = _tmp27_ * 100;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 4:
		{
			GtkComboBox* _tmp28_ = NULL;
			gint _tmp29_ = 0;
			_tmp28_ = self->priv->box_masa_saida;
			_tmp29_ = gtk_combo_box_get_active (_tmp28_);
			switch (_tmp29_) {
				case 0:
				{
					gdouble _tmp30_ = 0.0;
					_tmp30_ = aux;
					aux = _tmp30_ * 0.000001;
					break;
				}
				case 1:
				{
					gdouble _tmp31_ = 0.0;
					_tmp31_ = aux;
					aux = _tmp31_ * 0.0000098067;
					break;
				}
				case 2:
				{
					gdouble _tmp32_ = 0.0;
					_tmp32_ = aux;
					aux = _tmp32_ * 0.001;
					break;
				}
				case 3:
				{
					gdouble _tmp33_ = 0.0;
					_tmp33_ = aux;
					aux = _tmp33_ * 0.01;
					break;
				}
				case 4:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp34_ = self->priv->spin_masa;
	_tmp35_ = self->priv->lista_box_masa;
	_tmp35__length1 = self->priv->lista_box_masa_length1;
	_tmp36_ = self->priv->box_masa_entrada;
	_tmp37_ = self->priv->entry_masa_entrada;
	main_escribir_entrada (self, _tmp34_, _tmp35_, _tmp35__length1, _tmp36_, _tmp37_);
	_tmp38_ = aux;
	_tmp39_ = self->priv->spin_masa;
	_tmp40_ = self->priv->lista_box_masa;
	_tmp40__length1 = self->priv->lista_box_masa_length1;
	_tmp41_ = self->priv->box_masa_saida;
	_tmp42_ = self->priv->entry_masa_saida;
	main_escribir_saida (self, _tmp38_, _tmp39_, _tmp40_, _tmp40__length1, _tmp41_, _tmp42_);
}


void main_on_but_aplicar_densidad_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp25_ = NULL;
	gchar** _tmp26_ = NULL;
	gint _tmp26__length1 = 0;
	GtkComboBox* _tmp27_ = NULL;
	GtkEntry* _tmp28_ = NULL;
	gdouble _tmp29_ = 0.0;
	GtkSpinButton* _tmp30_ = NULL;
	gchar** _tmp31_ = NULL;
	gint _tmp31__length1 = 0;
	GtkComboBox* _tmp32_ = NULL;
	GtkEntry* _tmp33_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_densidad;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_densidad_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_densidad_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 1000;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 1000000;
					break;
				}
				case 3:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 1000000000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			_tmp9_ = self->priv->box_densidad_saida;
			_tmp10_ = gtk_combo_box_get_active (_tmp9_);
			switch (_tmp10_) {
				case 0:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 0.001;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 1000;
					break;
				}
				case 3:
				{
					gdouble _tmp13_ = 0.0;
					_tmp13_ = aux;
					aux = _tmp13_ * 1000000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			_tmp14_ = self->priv->box_densidad_saida;
			_tmp15_ = gtk_combo_box_get_active (_tmp14_);
			switch (_tmp15_) {
				case 0:
				{
					gdouble _tmp16_ = 0.0;
					_tmp16_ = aux;
					aux = _tmp16_ * 0.000001;
					break;
				}
				case 1:
				{
					gdouble _tmp17_ = 0.0;
					_tmp17_ = aux;
					aux = _tmp17_ * 0.001;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp18_ = 0.0;
					_tmp18_ = aux;
					aux = _tmp18_ * 1000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			_tmp19_ = self->priv->box_densidad_saida;
			_tmp20_ = gtk_combo_box_get_active (_tmp19_);
			switch (_tmp20_) {
				case 0:
				{
					gdouble _tmp21_ = 0.0;
					gdouble _tmp22_ = 0.0;
					_tmp21_ = aux;
					_tmp22_ = pow ((gdouble) 10, (gdouble) -9);
					aux = _tmp21_ * _tmp22_;
					break;
				}
				case 1:
				{
					gdouble _tmp23_ = 0.0;
					_tmp23_ = aux;
					aux = _tmp23_ * 0.000001;
					break;
				}
				case 2:
				{
					gdouble _tmp24_ = 0.0;
					_tmp24_ = aux;
					aux = _tmp24_ * 0.001;
					break;
				}
				case 3:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp25_ = self->priv->spin_densidad;
	_tmp26_ = self->priv->lista_box_densidad;
	_tmp26__length1 = self->priv->lista_box_densidad_length1;
	_tmp27_ = self->priv->box_densidad_entrada;
	_tmp28_ = self->priv->entry_densidad_entrada;
	main_escribir_entrada (self, _tmp25_, _tmp26_, _tmp26__length1, _tmp27_, _tmp28_);
	_tmp29_ = aux;
	_tmp30_ = self->priv->spin_densidad;
	_tmp31_ = self->priv->lista_box_densidad;
	_tmp31__length1 = self->priv->lista_box_densidad_length1;
	_tmp32_ = self->priv->box_densidad_saida;
	_tmp33_ = self->priv->entry_densidad_saida;
	main_escribir_saida (self, _tmp29_, _tmp30_, _tmp31_, _tmp31__length1, _tmp32_, _tmp33_);
}


void main_on_but_aplicar_velocidad_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp16_ = NULL;
	gchar** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	GtkComboBox* _tmp18_ = NULL;
	GtkEntry* _tmp19_ = NULL;
	gdouble _tmp20_ = 0.0;
	GtkSpinButton* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	GtkComboBox* _tmp23_ = NULL;
	GtkEntry* _tmp24_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_velocidad;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_velocidad_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_velocidad_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 0.277778;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 0.00027778;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			_tmp8_ = self->priv->box_velocidad_saida;
			_tmp9_ = gtk_combo_box_get_active (_tmp8_);
			switch (_tmp9_) {
				case 0:
				{
					gdouble _tmp10_ = 0.0;
					_tmp10_ = aux;
					aux = _tmp10_ * 3.6;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 0.001;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			_tmp12_ = self->priv->box_velocidad_saida;
			_tmp13_ = gtk_combo_box_get_active (_tmp12_);
			switch (_tmp13_) {
				case 0:
				{
					gdouble _tmp14_ = 0.0;
					_tmp14_ = aux;
					aux = _tmp14_ * 3600;
					break;
				}
				case 1:
				{
					gdouble _tmp15_ = 0.0;
					_tmp15_ = aux;
					aux = _tmp15_ * 1000;
					break;
				}
				case 2:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp16_ = self->priv->spin_velocidad;
	_tmp17_ = self->priv->lista_box_velocidad;
	_tmp17__length1 = self->priv->lista_box_velocidad_length1;
	_tmp18_ = self->priv->box_velocidad_entrada;
	_tmp19_ = self->priv->entry_velocidad_entrada;
	main_escribir_entrada (self, _tmp16_, _tmp17_, _tmp17__length1, _tmp18_, _tmp19_);
	_tmp20_ = aux;
	_tmp21_ = self->priv->spin_velocidad;
	_tmp22_ = self->priv->lista_box_velocidad;
	_tmp22__length1 = self->priv->lista_box_velocidad_length1;
	_tmp23_ = self->priv->box_velocidad_saida;
	_tmp24_ = self->priv->entry_velocidad_saida;
	main_escribir_saida (self, _tmp20_, _tmp21_, _tmp22_, _tmp22__length1, _tmp23_, _tmp24_);
}


void main_on_but_aplicar_area_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp17_ = NULL;
	gchar** _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
	GtkComboBox* _tmp19_ = NULL;
	GtkEntry* _tmp20_ = NULL;
	gdouble _tmp21_ = 0.0;
	GtkSpinButton* _tmp22_ = NULL;
	gchar** _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	GtkComboBox* _tmp24_ = NULL;
	GtkEntry* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_area;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_area_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_area_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 1000000;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 10000000000LL;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			_tmp8_ = self->priv->box_area_saida;
			_tmp9_ = gtk_combo_box_get_active (_tmp8_);
			switch (_tmp9_) {
				case 0:
				{
					gdouble _tmp10_ = 0.0;
					_tmp10_ = aux;
					aux = _tmp10_ * 0.000001;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 10000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			_tmp12_ = self->priv->box_area_saida;
			_tmp13_ = gtk_combo_box_get_active (_tmp12_);
			switch (_tmp13_) {
				case 0:
				{
					gdouble _tmp14_ = 0.0;
					gdouble _tmp15_ = 0.0;
					_tmp14_ = aux;
					_tmp15_ = pow ((gdouble) 10, (gdouble) -10);
					aux = _tmp14_ * _tmp15_;
					break;
				}
				case 1:
				{
					gdouble _tmp16_ = 0.0;
					_tmp16_ = aux;
					aux = _tmp16_ * 0.0001;
					break;
				}
				case 2:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp17_ = self->priv->spin_area;
	_tmp18_ = self->priv->lista_box_area;
	_tmp18__length1 = self->priv->lista_box_area_length1;
	_tmp19_ = self->priv->box_area_entrada;
	_tmp20_ = self->priv->entry_area_entrada;
	main_escribir_entrada (self, _tmp17_, _tmp18_, _tmp18__length1, _tmp19_, _tmp20_);
	_tmp21_ = aux;
	_tmp22_ = self->priv->spin_area;
	_tmp23_ = self->priv->lista_box_area;
	_tmp23__length1 = self->priv->lista_box_area_length1;
	_tmp24_ = self->priv->box_area_saida;
	_tmp25_ = self->priv->entry_area_saida;
	main_escribir_saida (self, _tmp21_, _tmp22_, _tmp23_, _tmp23__length1, _tmp24_, _tmp25_);
}


void main_on_but_aplicar_longitud_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	GtkComboBox* _tmp26_ = NULL;
	GtkEntry* _tmp27_ = NULL;
	gdouble _tmp28_ = 0.0;
	GtkSpinButton* _tmp29_ = NULL;
	gchar** _tmp30_ = NULL;
	gint _tmp30__length1 = 0;
	GtkComboBox* _tmp31_ = NULL;
	GtkEntry* _tmp32_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_longitud;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_longitud_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_longitud_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 1000;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 100000;
					break;
				}
				case 3:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 1000000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			_tmp9_ = self->priv->box_longitud_saida;
			_tmp10_ = gtk_combo_box_get_active (_tmp9_);
			switch (_tmp10_) {
				case 0:
				{
					gdouble _tmp11_ = 0.0;
					_tmp11_ = aux;
					aux = _tmp11_ * 0.001;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 100;
					break;
				}
				case 3:
				{
					gdouble _tmp13_ = 0.0;
					_tmp13_ = aux;
					aux = _tmp13_ * 1000;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			_tmp14_ = self->priv->box_longitud_saida;
			_tmp15_ = gtk_combo_box_get_active (_tmp14_);
			switch (_tmp15_) {
				case 0:
				{
					gdouble _tmp16_ = 0.0;
					_tmp16_ = aux;
					aux = _tmp16_ * 0.00001;
					break;
				}
				case 1:
				{
					gdouble _tmp17_ = 0.0;
					_tmp17_ = aux;
					aux = _tmp17_ * 0.01;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp18_ = 0.0;
					_tmp18_ = aux;
					aux = _tmp18_ * 10;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			_tmp19_ = self->priv->box_longitud_saida;
			_tmp20_ = gtk_combo_box_get_active (_tmp19_);
			switch (_tmp20_) {
				case 0:
				{
					gdouble _tmp21_ = 0.0;
					_tmp21_ = aux;
					aux = _tmp21_ * 0.000001;
					break;
				}
				case 1:
				{
					gdouble _tmp22_ = 0.0;
					_tmp22_ = aux;
					aux = _tmp22_ * 0.001;
					break;
				}
				case 2:
				{
					gdouble _tmp23_ = 0.0;
					_tmp23_ = aux;
					aux = _tmp23_ * 0.1;
					break;
				}
				case 3:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp24_ = self->priv->spin_longitud;
	_tmp25_ = self->priv->lista_box_longitud;
	_tmp25__length1 = self->priv->lista_box_longitud_length1;
	_tmp26_ = self->priv->box_longitud_entrada;
	_tmp27_ = self->priv->entry_longitud_entrada;
	main_escribir_entrada (self, _tmp24_, _tmp25_, _tmp25__length1, _tmp26_, _tmp27_);
	_tmp28_ = aux;
	_tmp29_ = self->priv->spin_longitud;
	_tmp30_ = self->priv->lista_box_longitud;
	_tmp30__length1 = self->priv->lista_box_longitud_length1;
	_tmp31_ = self->priv->box_longitud_saida;
	_tmp32_ = self->priv->entry_longitud_saida;
	main_escribir_saida (self, _tmp28_, _tmp29_, _tmp30_, _tmp30__length1, _tmp31_, _tmp32_);
}


void main_on_but_aplicar_tiempo_clicked (GtkWidget* window, Main* self) {
	gdouble aux = 0.0;
	GtkSpinButton* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GtkComboBox* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkSpinButton* _tmp35_ = NULL;
	gchar** _tmp36_ = NULL;
	gint _tmp36__length1 = 0;
	GtkComboBox* _tmp37_ = NULL;
	GtkEntry* _tmp38_ = NULL;
	gdouble _tmp39_ = 0.0;
	GtkSpinButton* _tmp40_ = NULL;
	gchar** _tmp41_ = NULL;
	gint _tmp41__length1 = 0;
	GtkComboBox* _tmp42_ = NULL;
	GtkEntry* _tmp43_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->spin_tiempo;
	_tmp1_ = gtk_spin_button_get_value (_tmp0_);
	aux = _tmp1_;
	_tmp2_ = self->priv->box_tiempo_entrada;
	_tmp3_ = gtk_combo_box_get_active (_tmp2_);
	switch (_tmp3_) {
		case 0:
		{
			GtkComboBox* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = self->priv->box_tiempo_saida;
			_tmp5_ = gtk_combo_box_get_active (_tmp4_);
			switch (_tmp5_) {
				case 0:
				{
					break;
				}
				case 1:
				{
					gdouble _tmp6_ = 0.0;
					_tmp6_ = aux;
					aux = _tmp6_ * 60;
					break;
				}
				case 2:
				{
					gdouble _tmp7_ = 0.0;
					_tmp7_ = aux;
					aux = _tmp7_ * 3600;
					break;
				}
				case 3:
				{
					gdouble _tmp8_ = 0.0;
					_tmp8_ = aux;
					aux = _tmp8_ * 0.041667;
					break;
				}
				case 4:
				{
					gdouble _tmp9_ = 0.0;
					_tmp9_ = aux;
					aux = _tmp9_ * 0.00011408;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 1:
		{
			GtkComboBox* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			_tmp10_ = self->priv->box_tiempo_saida;
			_tmp11_ = gtk_combo_box_get_active (_tmp10_);
			switch (_tmp11_) {
				case 0:
				{
					gdouble _tmp12_ = 0.0;
					_tmp12_ = aux;
					aux = _tmp12_ * 0.016667;
					break;
				}
				case 1:
				{
					break;
				}
				case 2:
				{
					gdouble _tmp13_ = 0.0;
					_tmp13_ = aux;
					aux = _tmp13_ * 60;
					break;
				}
				case 3:
				{
					gdouble _tmp14_ = 0.0;
					_tmp14_ = aux;
					aux = _tmp14_ * 0.00069444;
					break;
				}
				case 4:
				{
					gdouble _tmp15_ = 0.0;
					_tmp15_ = aux;
					aux = _tmp15_ * 0.0000019013;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 2:
		{
			GtkComboBox* _tmp16_ = NULL;
			gint _tmp17_ = 0;
			_tmp16_ = self->priv->box_tiempo_saida;
			_tmp17_ = gtk_combo_box_get_active (_tmp16_);
			switch (_tmp17_) {
				case 0:
				{
					gdouble _tmp18_ = 0.0;
					_tmp18_ = aux;
					aux = _tmp18_ * 0.00027778;
					break;
				}
				case 1:
				{
					gdouble _tmp19_ = 0.0;
					_tmp19_ = aux;
					aux = _tmp19_ * 0.016667;
					break;
				}
				case 2:
				{
					break;
				}
				case 3:
				{
					gdouble _tmp20_ = 0.0;
					_tmp20_ = aux;
					aux = _tmp20_ * 0.0000115741;
					break;
				}
				case 4:
				{
					gdouble _tmp21_ = 0.0;
					gdouble _tmp22_ = 0.0;
					_tmp21_ = aux;
					_tmp22_ = pow ((gdouble) 10, (gdouble) -8);
					aux = _tmp21_ * (3.168808781402895 * _tmp22_);
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 3:
		{
			GtkComboBox* _tmp23_ = NULL;
			gint _tmp24_ = 0;
			_tmp23_ = self->priv->box_tiempo_saida;
			_tmp24_ = gtk_combo_box_get_active (_tmp23_);
			switch (_tmp24_) {
				case 0:
				{
					gdouble _tmp25_ = 0.0;
					_tmp25_ = aux;
					aux = _tmp25_ * 24;
					break;
				}
				case 1:
				{
					gdouble _tmp26_ = 0.0;
					_tmp26_ = aux;
					aux = _tmp26_ * 1440;
					break;
				}
				case 2:
				{
					gdouble _tmp27_ = 0.0;
					_tmp27_ = aux;
					aux = _tmp27_ * 86400;
					break;
				}
				case 3:
				{
					break;
				}
				case 4:
				{
					gdouble _tmp28_ = 0.0;
					_tmp28_ = aux;
					aux = _tmp28_ * 0.00273785;
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case 4:
		{
			GtkComboBox* _tmp29_ = NULL;
			gint _tmp30_ = 0;
			_tmp29_ = self->priv->box_tiempo_saida;
			_tmp30_ = gtk_combo_box_get_active (_tmp29_);
			switch (_tmp30_) {
				case 0:
				{
					gdouble _tmp31_ = 0.0;
					_tmp31_ = aux;
					aux = _tmp31_ * 8766;
					break;
				}
				case 1:
				{
					gdouble _tmp32_ = 0.0;
					_tmp32_ = aux;
					aux = _tmp32_ * 525960;
					break;
				}
				case 2:
				{
					gdouble _tmp33_ = 0.0;
					_tmp33_ = aux;
					aux = _tmp33_ * 31557600;
					break;
				}
				case 3:
				{
					gdouble _tmp34_ = 0.0;
					_tmp34_ = aux;
					aux = _tmp34_ * 365.25;
					break;
				}
				case 4:
				{
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	_tmp35_ = self->priv->spin_tiempo;
	_tmp36_ = self->priv->lista_box_tiempo;
	_tmp36__length1 = self->priv->lista_box_tiempo_length1;
	_tmp37_ = self->priv->box_tiempo_entrada;
	_tmp38_ = self->priv->entry_tiempo_entrada;
	main_escribir_entrada (self, _tmp35_, _tmp36_, _tmp36__length1, _tmp37_, _tmp38_);
	_tmp39_ = aux;
	_tmp40_ = self->priv->spin_tiempo;
	_tmp41_ = self->priv->lista_box_tiempo;
	_tmp41__length1 = self->priv->lista_box_tiempo_length1;
	_tmp42_ = self->priv->box_tiempo_saida;
	_tmp43_ = self->priv->entry_tiempo_saida;
	main_escribir_saida (self, _tmp39_, _tmp40_, _tmp41_, _tmp41__length1, _tmp42_, _tmp43_);
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* app = NULL;
	Main* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_new ();
	app = _tmp0_;
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return main_main (argv, argc);
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
}


static void main_instance_init (Main * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar** _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar** _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar** _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar** _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar** _tmp45_ = NULL;
	gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gchar** _tmp49_ = NULL;
	self->priv = MAIN_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("MegaPascal");
	_tmp1_ = g_strdup ("Pascal");
	_tmp2_ = g_strdup ("Bar");
	_tmp3_ = g_strdup ("atm");
	_tmp4_ = g_strdup ("kgf/cm²");
	_tmp5_ = g_strdup ("kgf/m²");
	_tmp6_ = g_strdup ("mmHG");
	_tmp7_ = g_new0 (gchar*, 7 + 1);
	_tmp7_[0] = _tmp0_;
	_tmp7_[1] = _tmp1_;
	_tmp7_[2] = _tmp2_;
	_tmp7_[3] = _tmp3_;
	_tmp7_[4] = _tmp4_;
	_tmp7_[5] = _tmp5_;
	_tmp7_[6] = _tmp6_;
	self->priv->lista_box_presion = _tmp7_;
	self->priv->lista_box_presion_length1 = 7;
	self->priv->_lista_box_presion_size_ = self->priv->lista_box_presion_length1;
	_tmp8_ = g_strdup ("km³");
	_tmp9_ = g_strdup ("m³");
	_tmp10_ = g_strdup ("litro");
	_tmp11_ = g_strdup ("dm³");
	_tmp12_ = g_strdup ("cm³");
	_tmp13_ = g_new0 (gchar*, 5 + 1);
	_tmp13_[0] = _tmp8_;
	_tmp13_[1] = _tmp9_;
	_tmp13_[2] = _tmp10_;
	_tmp13_[3] = _tmp11_;
	_tmp13_[4] = _tmp12_;
	self->priv->lista_box_volumen = _tmp13_;
	self->priv->lista_box_volumen_length1 = 5;
	self->priv->_lista_box_volumen_size_ = self->priv->lista_box_volumen_length1;
	_tmp14_ = g_strdup ("Tonelada");
	_tmp15_ = g_strdup ("kN");
	_tmp16_ = g_strdup ("kg");
	_tmp17_ = g_strdup ("hg");
	_tmp18_ = g_strdup ("g");
	_tmp19_ = g_new0 (gchar*, 5 + 1);
	_tmp19_[0] = _tmp14_;
	_tmp19_[1] = _tmp15_;
	_tmp19_[2] = _tmp16_;
	_tmp19_[3] = _tmp17_;
	_tmp19_[4] = _tmp18_;
	self->priv->lista_box_masa = _tmp19_;
	self->priv->lista_box_masa_length1 = 5;
	self->priv->_lista_box_masa_size_ = self->priv->lista_box_masa_length1;
	_tmp20_ = g_strdup ("N");
	_tmp21_ = g_strdup ("kgf");
	_tmp22_ = g_strdup ("Dyna");
	_tmp23_ = g_strdup ("Joule/metro");
	_tmp24_ = g_strdup ("Pa/m²");
	_tmp25_ = g_new0 (gchar*, 5 + 1);
	_tmp25_[0] = _tmp20_;
	_tmp25_[1] = _tmp21_;
	_tmp25_[2] = _tmp22_;
	_tmp25_[3] = _tmp23_;
	_tmp25_[4] = _tmp24_;
	self->priv->lista_box_fuerza = _tmp25_;
	self->priv->lista_box_fuerza_length1 = 5;
	self->priv->_lista_box_fuerza_size_ = self->priv->lista_box_fuerza_length1;
	_tmp26_ = g_strdup ("hora");
	_tmp27_ = g_strdup ("min");
	_tmp28_ = g_strdup ("s");
	_tmp29_ = g_strdup ("dia");
	_tmp30_ = g_strdup ("ano");
	_tmp31_ = g_new0 (gchar*, 5 + 1);
	_tmp31_[0] = _tmp26_;
	_tmp31_[1] = _tmp27_;
	_tmp31_[2] = _tmp28_;
	_tmp31_[3] = _tmp29_;
	_tmp31_[4] = _tmp30_;
	self->priv->lista_box_tiempo = _tmp31_;
	self->priv->lista_box_tiempo_length1 = 5;
	self->priv->_lista_box_tiempo_size_ = self->priv->lista_box_tiempo_length1;
	_tmp32_ = g_strdup ("km/h");
	_tmp33_ = g_strdup ("m/s");
	_tmp34_ = g_strdup ("km/s");
	_tmp35_ = g_new0 (gchar*, 3 + 1);
	_tmp35_[0] = _tmp32_;
	_tmp35_[1] = _tmp33_;
	_tmp35_[2] = _tmp34_;
	self->priv->lista_box_velocidad = _tmp35_;
	self->priv->lista_box_velocidad_length1 = 3;
	self->priv->_lista_box_velocidad_size_ = self->priv->lista_box_velocidad_length1;
	_tmp36_ = g_strdup ("km");
	_tmp37_ = g_strdup ("m");
	_tmp38_ = g_strdup ("cm");
	_tmp39_ = g_strdup ("mm");
	_tmp40_ = g_new0 (gchar*, 4 + 1);
	_tmp40_[0] = _tmp36_;
	_tmp40_[1] = _tmp37_;
	_tmp40_[2] = _tmp38_;
	_tmp40_[3] = _tmp39_;
	self->priv->lista_box_longitud = _tmp40_;
	self->priv->lista_box_longitud_length1 = 4;
	self->priv->_lista_box_longitud_size_ = self->priv->lista_box_longitud_length1;
	_tmp41_ = g_strdup ("g/cm³");
	_tmp42_ = g_strdup ("kg/m³");
	_tmp43_ = g_strdup ("g/m³");
	_tmp44_ = g_strdup ("mg/m³");
	_tmp45_ = g_new0 (gchar*, 4 + 1);
	_tmp45_[0] = _tmp41_;
	_tmp45_[1] = _tmp42_;
	_tmp45_[2] = _tmp43_;
	_tmp45_[3] = _tmp44_;
	self->priv->lista_box_densidad = _tmp45_;
	self->priv->lista_box_densidad_length1 = 4;
	self->priv->_lista_box_densidad_size_ = self->priv->lista_box_densidad_length1;
	_tmp46_ = g_strdup ("km²");
	_tmp47_ = g_strdup ("m²");
	_tmp48_ = g_strdup ("cm²");
	_tmp49_ = g_new0 (gchar*, 3 + 1);
	_tmp49_[0] = _tmp46_;
	_tmp49_[1] = _tmp47_;
	_tmp49_[2] = _tmp48_;
	self->priv->lista_box_area = _tmp49_;
	self->priv->lista_box_area_length1 = 3;
	self->priv->_lista_box_area_size_ = self->priv->lista_box_area_length1;
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	self->priv->lista_box_presion = (_vala_array_free (self->priv->lista_box_presion, self->priv->lista_box_presion_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_volumen = (_vala_array_free (self->priv->lista_box_volumen, self->priv->lista_box_volumen_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_masa = (_vala_array_free (self->priv->lista_box_masa, self->priv->lista_box_masa_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_fuerza = (_vala_array_free (self->priv->lista_box_fuerza, self->priv->lista_box_fuerza_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_tiempo = (_vala_array_free (self->priv->lista_box_tiempo, self->priv->lista_box_tiempo_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_velocidad = (_vala_array_free (self->priv->lista_box_velocidad, self->priv->lista_box_velocidad_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_longitud = (_vala_array_free (self->priv->lista_box_longitud, self->priv->lista_box_longitud_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_densidad = (_vala_array_free (self->priv->lista_box_densidad, self->priv->lista_box_densidad_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lista_box_area = (_vala_array_free (self->priv->lista_box_area, self->priv->lista_box_area_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (self->priv->entry_presion_entrada);
	_g_object_unref0 (self->priv->entry_presion_saida);
	_g_object_unref0 (self->priv->entry_volumen_entrada);
	_g_object_unref0 (self->priv->entry_volumen_saida);
	_g_object_unref0 (self->priv->entry_masa_entrada);
	_g_object_unref0 (self->priv->entry_masa_saida);
	_g_object_unref0 (self->priv->entry_fuerza_entrada);
	_g_object_unref0 (self->priv->entry_fuerza_saida);
	_g_object_unref0 (self->priv->entry_densidad_entrada);
	_g_object_unref0 (self->priv->entry_densidad_saida);
	_g_object_unref0 (self->priv->entry_velocidad_entrada);
	_g_object_unref0 (self->priv->entry_velocidad_saida);
	_g_object_unref0 (self->priv->entry_area_entrada);
	_g_object_unref0 (self->priv->entry_area_saida);
	_g_object_unref0 (self->priv->entry_longitud_entrada);
	_g_object_unref0 (self->priv->entry_longitud_saida);
	_g_object_unref0 (self->priv->entry_tiempo_entrada);
	_g_object_unref0 (self->priv->entry_tiempo_saida);
	_g_object_unref0 (self->priv->spin_presion);
	_g_object_unref0 (self->priv->spin_masa);
	_g_object_unref0 (self->priv->spin_fuerza);
	_g_object_unref0 (self->priv->spin_volumen);
	_g_object_unref0 (self->priv->spin_densidad);
	_g_object_unref0 (self->priv->spin_area);
	_g_object_unref0 (self->priv->spin_longitud);
	_g_object_unref0 (self->priv->spin_tiempo);
	_g_object_unref0 (self->priv->spin_velocidad);
	_g_object_unref0 (self->priv->box_presion_entrada);
	_g_object_unref0 (self->priv->box_presion_saida);
	_g_object_unref0 (self->priv->box_fuerza_entrada);
	_g_object_unref0 (self->priv->box_fuerza_saida);
	_g_object_unref0 (self->priv->box_masa_entrada);
	_g_object_unref0 (self->priv->box_masa_saida);
	_g_object_unref0 (self->priv->box_densidad_entrada);
	_g_object_unref0 (self->priv->box_densidad_saida);
	_g_object_unref0 (self->priv->box_volumen_entrada);
	_g_object_unref0 (self->priv->box_volumen_saida);
	_g_object_unref0 (self->priv->box_velocidad_entrada);
	_g_object_unref0 (self->priv->box_velocidad_saida);
	_g_object_unref0 (self->priv->box_area_entrada);
	_g_object_unref0 (self->priv->box_area_saida);
	_g_object_unref0 (self->priv->box_longitud_entrada);
	_g_object_unref0 (self->priv->box_longitud_saida);
	_g_object_unref0 (self->priv->box_tiempo_entrada);
	_g_object_unref0 (self->priv->box_tiempo_saida);
	_g_object_unref0 (self->priv->dialog);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



