/* cambio.c generated by valac 0.34.7, the Vala compiler
 * generated from cambio.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * main.c
 * Copyright (C) 2018 Taylan Branco Meurer <tbmeurer@gmail.com>
 *
 * cambio is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * cambio is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <stdio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define MAIN_TYPE_COLUMN (main_column_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};

struct _MainPrivate {
	gchar** box_presion;
	gint box_presion_length1;
	gint _box_presion_size_;
	GtkEntry* entry_presion_entrada;
};

typedef enum  {
	MAIN_COLUMN_Presion_enum
} MainColumn;


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY
};
static GType main_column_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define MAIN_UI_FILE "cambio.ui"
Main* main_new (void);
Main* main_construct (GType object_type);
void main_on_destroy (GtkWidget* window, Main* self);
void main_on_but_aplicar_presion_clicked (GtkWidget* window, Main* self);
static gint main_main (gchar** args, int args_length1);
static void main_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static GType main_column_get_type (void) {
	static volatile gsize main_column_type_id__volatile = 0;
	if (g_once_init_enter (&main_column_type_id__volatile)) {
		static const GEnumValue values[] = {{MAIN_COLUMN_Presion_enum, "MAIN_COLUMN_Presion_enum", "presion-enum"}, {0, NULL, NULL}};
		GType main_column_type_id;
		main_column_type_id = g_enum_register_static ("MainColumn", values);
		g_once_init_leave (&main_column_type_id__volatile, main_column_type_id);
	}
	return main_column_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	GError * _inner_error_ = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	{
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp0_ = NULL;
		GObject* _tmp1_ = NULL;
		GtkEntry* _tmp2_ = NULL;
		GtkWindow* window = NULL;
		GObject* _tmp3_ = NULL;
		GtkWindow* _tmp4_ = NULL;
		GtkWindow* _tmp5_ = NULL;
		_tmp0_ = gtk_builder_new ();
		builder = _tmp0_;
		gtk_builder_add_from_file (builder, MAIN_UI_FILE, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (builder);
			goto __catch0_g_error;
		}
		gtk_builder_connect_signals (builder, self);
		_tmp1_ = gtk_builder_get_object (builder, "entry_presion_entrada");
		_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp1_) : NULL);
		_g_object_unref0 (self->priv->entry_presion_entrada);
		self->priv->entry_presion_entrada = _tmp2_;
		_tmp3_ = gtk_builder_get_object (builder, "window");
		_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp3_) : NULL);
		window = _tmp4_;
		_tmp5_ = window;
		gtk_widget_show_all ((GtkWidget*) _tmp5_);
		_g_object_unref0 (window);
		_g_object_unref0 (builder);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = stderr;
		_tmp7_ = e;
		_tmp8_ = _tmp7_->message;
		fprintf (_tmp6_, "Could not load UI: %s\n", _tmp8_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


void main_on_destroy (GtkWidget* window, Main* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	gtk_main_quit ();
}


void main_on_but_aplicar_presion_clicked (GtkWidget* window, Main* self) {
	GtkEntry* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	_tmp0_ = self->priv->entry_presion_entrada;
	gtk_entry_set_text (_tmp0_, "Yes");
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* app = NULL;
	Main* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_new ();
	app = _tmp0_;
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return main_main (argv, argc);
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
}


static void main_instance_init (Main * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	self->priv = MAIN_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("MegaPascal");
	_tmp1_ = g_strdup ("Pascal");
	_tmp2_ = g_strdup ("Bar");
	_tmp3_ = g_strdup ("atm");
	_tmp4_ = g_strdup ("kgf/cm²");
	_tmp5_ = g_strdup ("kgf/m²");
	_tmp6_ = g_strdup ("mmHG");
	_tmp7_ = g_new0 (gchar*, 7 + 1);
	_tmp7_[0] = _tmp0_;
	_tmp7_[1] = _tmp1_;
	_tmp7_[2] = _tmp2_;
	_tmp7_[3] = _tmp3_;
	_tmp7_[4] = _tmp4_;
	_tmp7_[5] = _tmp5_;
	_tmp7_[6] = _tmp6_;
	self->priv->box_presion = _tmp7_;
	self->priv->box_presion_length1 = 7;
	self->priv->_box_presion_size_ = self->priv->box_presion_length1;
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	self->priv->box_presion = (_vala_array_free (self->priv->box_presion, self->priv->box_presion_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (self->priv->entry_presion_entrada);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



